version: '3.7'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_sibdev
      - POSTGRES_PASSWORD=test_sibdev_password
      - POSTGRES_DB=test_sibdev
  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
      driver: local